apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/fluxcd/kustomize-controller/releases/download/v1.0.0-rc.4/kustomize-controller.crds.yaml
- https://github.com/fluxcd/kustomize-controller/releases/download/v1.0.0-rc.4/kustomize-controller.deployment.yaml
- account.yaml
transformers:
- labels.yaml
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: kustomize-controller
  path: patch.yaml
